- liquid/templates/registration/login.html
> login page: Add link to join page per #276

- liquid/static/css/bootstrap.min.css
Also repositioned nav controls so they're in the center of each carousel frame.
> Forced display:block on nav to stop flickering

- liquid/settings.py
Temporary fix until auth is moved onto Crowd.
> Use working LDAP auth settings. Fixes #283.

- Dockerfile
- docker/exim.sh
Update the Dockerfile to install and configure the exim4 mail server. It will send via the CITES Express SMTP gateway.
> Install exim4 within Docker

- Dockerfile
- liquid/settings.py
> settings.py: pull SMTP host from environment

- Dockerfile
Needed for resume book to work.
> dockerfile: install imagemagick

- setup.py
LOGO_STORAGE_LOCATION missing from setup.py, was readded
> added logo storage location to setup.py

- liquid/urls.py
@colegleason @achalv Care to comment? (If I don't see anything in the next hour, I'm merging.)
> Add mockmania redirect

- liquid/static/js/duckarmy.js
- liquid/templates/intranet/quote/base.html
Another late night in the ACM office. :stuck_out_tongue_winking_eye:
> [Quote DB] Duck army easter egg

- liquid/static/css/sponsors.css
> Refactor out grid resizing JS

- liquid/urls.py
Should be a pretty straightforward change.
@sskhandek Can you double-check that I didn't delete anything important? Thanks! :+1:
> Remove old URL redirects

- liquid/intranet/caffeine_manager/soda/views.py
- liquid/intranet/caffeine_manager/views.py
- liquid/intranet/models.py
@sskhandek, Can you look over this and let me know if I missed anything?
[Hotfix] since things are currently broken.
> [Hotfix] Split votes and vending into separate tables

- liquid/templates/base.html
- liquid/templates/conf/base.html
- liquid/templates/conf/landing.html
- liquid/templates/conference/base.html
- liquid/templates/conference/landing.html
Chrome CSP enforcement was causing issues with logging into the Intranet.
Reported by @sskhandek
> Hotfix for chrome CSPs

- liquid/templates/intranet/resume_manager/accounts.html
> Resume manager, part 1

- liquid/intranet/resume_manager/views.py
- liquid/scripts/send_job_email.py
Refactoring a few job-related files to reduce the likelihood of future/untraceable errors.
> Minor refactor

- liquid/intranet/resume_manager/views.py
- liquid/templates/intranet/resume_manager/accounts.html
Part 2 of issue #332 (sorting + expiry warnings)
> Resume manager, part 2

- Dockerfile
- liquid/intranet/caffeine_manager/trays/views.py
@milanocookies93 Care to review?
@ajmadsen or Rohan Kapoor may need to set up an SSH key to the Caffeine machine (dep-03?) for this to work.
> Implement forcevend script

- Dockerfile
Per @colegleason's comments on #351
> Revert #351's changes to Dockerfile

- Dockerfile
- liquid/intranet/caffeine_manager/trays/views.py
Merging this now; @milanocookies93 @colegleason @rohankapoorcom @sskhandek feel free to review + comment if I missed something
> (Attempt to) fix Caffeine Manager force-vending

- README.md
since we use some outdated modules
> Update README.md to force use python2.7
